apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: my-priv-sa
  namespace: {{ $.Values.namespace }} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:anyuid
  namespace: {{ $.Values.namespace }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: my-priv-sa
  namespace: {{ $.Values.namespace }}  
