apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysvc
  name: mysvc
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mydeployment
  type: ClusterIP
status:
  loadBalancer: {}
